# Generated by Django 6.0.1 on 2026-01-17 01:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movies/posters/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/reviews/', validators=[core.validators.validate_image_file]),
        ),
    ]
